/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sc;

/**
 *
 * @author xin
 */
public enum CodeCheckProp {
    // FOR SIMPLE OK/CANCEL DIALOG BOXES
    OK_PROMPT,
    CANCEL_PROMPT,
    
    HOME_BUTTON,PREVIOUS_BUTTON,NEXT_BUTTON,
    // THESE ARE FOR TEXT PARTICULAR TO THE APP'S WORKSPACE CONTROLS
    SLIDES_HEADER_TEXT,
    ADD_ALL_IMAGES_BUTTON_TEXT,
    ADD_IMAGE_BUTTON_TEXT,
    REMOVE_IMAGE_BUTTON_TEXT,
    FILE_NAME_COLUMN_TEXT,
    CAPTION_COLUMN_TEXT,
    ORIGINAL_WIDTH_COLUMN_TEXT,
    ORIGINAL_HEIGHT_COLUMN_TEXT,
    CURRENT_WIDTH_COLUMN_TEXT,
    CURRENT_HEIGHT_COLUMN_TEXT,
    FILE_NAME_PROMPT_TEXT,
    PATH_PROMPT_TEXT,
    CAPTION_PROMPT_TEXT,
    ORIGINAL_WIDTH_PROMPT_TEXT,
    ORIGINAL_HEIGHT_PROMPT_TEXT,
    CURRENT_WIDTH_PROMPT_TEXT,
    CURRENT_HEIGHT_PROMPT_TEXT,
    UPDATE_BUTTON_TEXT,
    
    // FOR OTHER INTERACTIONS
    APP_PATH_WORK,
    INVALID_IMAGE_PATH_TITLE,
    INVALID_IMAGE_PATH_MESSAGE
}
